type = "javascript"
account_id = "2ae5ddc12fe01a282dd014d39792077a"
workers_dev = true
kv-namespaces = [ 
	 { binding = "STORE", id = "d318bb77cf8c4d398b325e49b6e13f3b" } 
]

[site]
bucket = "./client/dist"
entry-point = "./server"

[env.test]
name = "sunpeep-test"

[env.live]
name = "sunpeep"
